name: Publish gcp-cloud-logger to PyPI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Setup docker build
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pypa/build
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
          python -m pip install -r requirements.txt

      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      # - name: Publish package to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
